### ISSUE TITLE
Passing environment variables during Environment creation

### ISSUE THREAD

**Issue by cemo** [ingenieux/beanstalker#102]
Hi, 

Is it possible to add documentation regarding how to add environment variables during environment creation.

Thanks

**Comment by aldrinleal** [comment]
Are we talking about this guy, right?

http://beanstalker.ingenieux.com.br/beanstalk-maven-plugin/create-environment-mojo.html#optionSettings

> optionSettings:
> 
> Configuration Option Settings. Will evaluate as such:
> 
> If empty, will lookup for beanstalk.env.aws.x.y variable in the context, and it will map this variable to 
> namespace [aws.x], under option name y, unless there's an alias set.

**Comment by cemo** [comment]
```
               <optionSetting>
                  <optionName>beanstalk.env.CEMO_VARIABLE</optionName>
                  <value>DEMO</value>
                </optionSetting>
```

Will this create a variable `CEMO_VARIABLE` with value `DEMO`? Or could you help me please?

**Comment by aldrinleal** [comment]
Shortest path (not sure, I need to review):

```xml
<properties>
  <beanstalk.env.aws.CEMO_VARIABLE>DEMO</beanstalk.env.aws.CEMO_VARIABLE>
</properties>
```
If you've got an existing env, dump-properties might help you:

http://docs.ingenieux.com.br/project/beanstalker/managing-environments.html

**Comment by cemo** [comment]
<3

**Comment by aldrinleal** [comment]
So, how did it end up? How did you solve it?

**Comment by cemo** [comment]
I first declared a property and then used dump-properties. I used as in the same way in the output and it worked. 

But I am not sure whether it is working by `put environment` or not. But It worked with `create`.
