### ISSUE TITLE
Timeout uploading source

### ISSUE THREAD

**Issue by damonridenow** [ingenieux/beanstalker#105]
i'm trying to upload an application with

mvn beanstalk:upload-source-bundle

but upload never starts, and i get timeout messages.
I tried also from a different connection (fastweb in italy seems to have problems with the AWS cli, for some operations) but i had the same result.

Thanks for the help.

Log attached
[result.txt](https://github.com/ingenieux/beanstalker/files/385775/result.txt)

**Comment by aldrinleal** [comment]
if your bundle is pretty small, disable multipart upload (see the closed issues for this)

**Comment by damonridenow** [comment]
thanks, it seems to work! i'm facing an Access Denied error no, but issue resolved!
:)
