### ISSUE TITLE
Update dependency for beanstalk-maven-plugin to use com.amazonaws:aws-java-ask:1.11.525

### ISSUE THREAD

**Issue by marioja** [ingenieux/beanstalker#116]
I need to deploy to new regions that are not defined in the com.amazonaws:aws-java-sdk:1.10.68 upon which br.com.ingenieux:beanstalk-maven-plugin:1.5.0 depends.  I have overridden the dependency in the plugin section of my application but I am not sure if this is FULLY supported and it would be nice if it were the default.

**Comment by aldrinleal** [comment]
https://github.com/ingenieux/beanstalker/issues/114

**Comment by aldrinleal** [comment]
Pull requests are welcome
