### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [ingenieux/beanstalker#120]
Hi
The following lines have cryptographic API misuses. <br> File name => beanstalk-maven-plugin/src/main/java/br/com/ingenieux/mojo/beanstalk/bundle/RequestSignerBase.java: Line number => 84: API name => SecretKeySpec:<BR> File name => beanstalk-maven-plugin/src/main/java/br/com/ingenieux/mojo/beanstalk/bundle/RequestSignerBase.java: Line number => 84: API name => SecretKeySpec:<BR>

**Comment by aldrinleal** [comment]
Can you give me more detail about this?

**Comment by aldrinleal** [comment]
[Oh](https://github.com/mob41/broadlink-java-api/issues/22#issuecomment-507780296)
