### ISSUE TITLE
Security Group Validity Check

### ISSUE THREAD

**Issue by edwinquaihoi** [ingenieux/beanstalker#125]
Hi I am facing an issue when using the replace-environment goal ... somewhere along the way, line 133 in the AbstractBeanstalkMojo class is being called to regex check the names of security groups which fails for my environment because our security group ids (sg-0f8c950bc7329a653,sg-06d4615187690e062) don't match the regex.

Do we need this validation line in the code?

`Validate.isTrue(securityGroup.matches("^sg-\\p{XDigit}{8}(,sg-\\p{XDigit}{8})*$"), "Invalid Security Group Spec: " + securityGroup);`

**Comment by aldrinleal** [comment]
I knew that sometimes my code would bite me! Could do a PR? From a first
glance, replacing "{8}" with "{8,16}" twice sounds like a reasonable fix
(although not perfect)

**Comment by aldrinleal** [comment]
oh nvm. publishing a new release/fix

**Comment by edwinquaihoi** [comment]
Thanks @aldrinleal , are you going to remove the code or patch the regex? Our security groups have more than 16 XDigits.

**Comment by aldrinleal** [comment]
Nice catch. I was under the impression it was 16, but [amazon said its now 17 instead](https://aws.amazon.com/blogs/compute/longer-resource-ids-in-2018-for-amazon-ec2-amazon-ebs-and-amazon-vpc/)

**Comment by aldrinleal** [comment]
[This should do the trick](https://github.com/ingenieux/beanstalker/commit/c7e9056162df3ed06849872ff10834ae001443f1)

(and I've had to bump some plugins in the way for the build to proceed - I believe its fixed, but we never know...)

**Comment by edwinquaihoi** [comment]
Thanks @aldrinleal really appreciate the quick turnaround.

**Comment by aldrinleal** [comment]
It took a while, had to update plugins and fix some javadocs, but I just released it. Should be in central in a couple of hours
