### ISSUE TITLE
cnamePrefix not working?

### ISSUE THREAD

**Issue by klemensz** [ingenieux/beanstalker#49]
I cannot get the update-environment to work. It seems that my artifact ID is always taken as the cname prefix.

    [INFO] --- beanstalk-maven-plugin:1.3.1:update-environment (default-cli) @ my_artifact ---
    [INFO] ... with status *NOT* set to 'Terminated'
    [INFO] ... with cname set to 'my_artifact.elasticbeanstalk.com'
    ...
    Caused by: org.apache.maven.plugin.MojoExecutionException: No environments found
	at br.com.ingenieux.mojo.beanstalk.AbstractBeanstalkMojo.handleNonSingle(AbstractBeanstalkMojo.java:71)
	at br.com.ingenieux.mojo.beanstalk.AbstractBeanstalkMojo.handleResults(AbstractBeanstalkMojo.java:63)
	at br.com.ingenieux.mojo.beanstalk.AbstractBeanstalkMojo.lookupEnvironment(AbstractBeanstalkMojo.java:53)
	at br.com.ingenieux.mojo.beanstalk.AbstractNeedsEnvironmentMojo.configure(AbstractNeedsEnvironmentMojo.java:59)
	... 22 more

I tried setting the cnamePrefix in the pom:
```xml
				<plugin>
			    	<groupId>br.com.ingenieux</groupId>
			    	<artifactId>beanstalk-maven-plugin</artifactId>
			    	<version>1.3.1</version>
			    	<configuration>
			        	<applicationName>My Awesome Webapp</applicationName>
			        	<cnamePrefix>my-awesome-webapp</cnamePrefix>
			        	<region>eu-west-1</region>
			       		<verbose>true</verbose>
			        	<s3Bucket>some-bucket-here</s3Bucket>
	          			<s3Key>${project.artifactId}/${project.build.finalName}-${maven.build.timestamp}.war</s3Key>
			        </configuration>
			    </plugin>
```

But also with the command line:
   
    mvn beanstalk:upload-source-bundle beanstalk:create-application-version beanstalk:update-environment -Dbeanstalk.cnamePrefix=my-awesome-webapp

**Comment by codedoge** [comment]
With version 1.5.6 it worked for me by setting property 
`<beanstalk.environmentRef>[my environment name]</beanstalk.environmentRef>`
It targets with fully matching regular expression the environment name as displayed with goal describe-environments
