### ISSUE TITLE
Cannot provide EB properties with '.' in name on the command line

### ISSUE THREAD

**Issue by s-nel** [ingenieux/beanstalker#57]
Beanstalker will take any Java property with prefix "beanstalk.env.aws" and try to interpret it as a name.space.key=value. With this mechanism there is no way to represent keys that contain a dot character. For example {namespace: "aws:elasticbeanstalk:application:environment", key: "authdb.user"} would be passed as "beanstalk.env.aws.elasticbeanstalk.application.environment.authdb.user=val" and will be interpreted as {namespace "aws:elasticbeanstalk:application:environment:authdb", key: "user"}

**Comment by aldrinleal** [comment]
Unfortunately, this is a limitation. I'm open to ideas, though

**Comment by aldrinleal** [comment]
Actually, on 1.4.1-SNAPSHOT there's a workaround:

```
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>br.com.ingenieux</groupId>
                    <artifactId>beanstalk-maven-plugin</artifactId>
                    <inherited>true</inherited>
                    <version>1.4.1-SNAPSHOT</version>
                    <configuration>
                    	<tags>
                    		<Uses>ingenieux Beanstalker at http://beanstalker.ingenieux.com.br/</Uses>
                    	</tags>
                    	<configurableOptionSettings>
                    		<configurableOptionSetting>
                    			<alias>beanstalkx.serviceRole</alias>
                    			<namespace>aws:elasticbeanstalk:environment</namespace>
                    			<optionName>ServiceRole</optionName>
                    		</configurableOptionSetting>
                    	</configurableOptionSettings>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
```

Defining this allows you to map ```beanstalkx.serviceRole``` property into the Configuration Option Setting.
