### ISSUE TITLE
Configure elastic load balancer log shipping to S3

### ISSUE THREAD

**Issue by vadimb111** [ingenieux/beanstalker#60]
Hi,

We use beanstalker extensively and it's a great product. I'm trying to automate log shipping to S3, it's a load balancer property. Unfortunately it doesn't seem that beanstalker supports it. Could you please advise if you have any solutions for this

Thanks,
-Vadim

**Comment by aldrinleal** [comment]
Thanks.

Vadim, is it supported by any of [those guys here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html)?
