### ISSUE TITLE
fast-deploy should use beanstalk.versionLabel

### ISSUE THREAD

**Issue by endrec** [ingenieux/beanstalker#61]
Specifying beanstalk.versionLabel with the fast-deploy, replace-environment goals causes exception:
com.amazonaws.AmazonServiceException: No Application Version named 'xxx' found.

fast-deploy should observe beanstalk.versionLabel parameter.

**Comment by aldrinleal** [comment]
fast-deploy doesn't allow you to create versions. the version itself is the
git commitId

and btw, bit.ly/bringgitback as even AWS keeps telling me its "deprecated"


--
-- Aldrin Leal, <aldrin@leal.eng.br>
Master your EC2-fu! Get the latest ekaterminal public beta
http://www.ingenieux.com.br/products/ekaterminal/
