### ISSUE TITLE
Dropwizard / Docker example references solutionStack that doesn't exist

### ISSUE THREAD

**Issue by thesmith** [ingenieux/beanstalker#62]
According to http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html, the solutionStack referenced was removed a couple of days ago: https://github.com/ingenieux/beanstalker/blob/master/elasticbeanstalk-docker-dropwizard-webapp-archetype/src/main/resources/archetype-resources/pom.xml#L32

I'm trying 'Single Container Docker 1.6 version 1.4.3' but that's not working out either:

    Caused by: com.amazonaws.AmazonServiceException: No Solution Stack named 'Single Container Docker 1.6 version 1.4.3' found. (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: f8528a27-14f5-11e5-9189-8d36c0c33eea)

**Comment by thesmith** [comment]
I found it!

'64bit Amazon Linux 2015.03 v1.4.3 running Docker 1.6.2'

**Comment by thesmith** [comment]
This is now deprecated by #65

**Comment by aldrinleal** [comment]
And further complicated by multicontainer
