### ISSUE TITLE
ReplaceEnvironment fails if Worker tier presented

### ISSUE THREAD

**Issue by mkalinin** [ingenieux/beanstalker#67]
hello guys,

I tried to use `ReplaceEnvironment` for our app and it fails with `NPE`. The reason is related to Worker tier which doesn't have a `cname` attribute (it's always `null`)
If you change this [line](https://github.com/ingenieux/beanstalker/blob/master/beanstalk-maven-plugin/src/main/java/br/com/ingenieux/mojo/beanstalk/env/ReplaceEnvironmentMojo.java#L536) this way:
```
if (cnameToMatch.equals(envDesc.getCNAME())) {
```
I believe it will work.
Will you do it shortly or do you have some other plans on this fix?

Thanks in advance

**Comment by aldrinleal** [comment]
ReplaceEnvironment doesn't apply to Worker Environments.

--
-- Aldrin Leal, <aldrin@leal.eng.br> / http://about.me/aldrinleal

**Comment by mkalinin** [comment]
Yes, I didn't try to apply it to Worker. But when I try to apply it to the Web tier it turns out with NPE in a case if we have a Worker tier for this application.
The line I have pointed at checks `cname` against all environment tiers of the app and first tier it met in my case is Worker which `cname` value is `null`.

**Comment by aldrinleal** [comment]
Oh, got it. Can you issue me a PR (and try to test it please :])?

I should be revisiting my projects later this week and I'll look into yours

--
-- Aldrin Leal, <aldrin@leal.eng.br> / http://about.me/aldrinleal

**Comment by mkalinin** [comment]
Done https://github.com/ingenieux/beanstalker/pull/68
Thanks a lot for your support

**Comment by mkalinin** [comment]
@aldrinleal could you please give me a link to repository containing snapshots to test #68 merge?

**Comment by aldrinleal** [comment]
@mkalinin,

I didn't publish snapshots yet, but you can install it locally:

$ git clone git@github.com:ingenieux/beanstalker.git
$ mvn clean package install -DskipTests

Let me know if you run into any problems

**Comment by mkalinin** [comment]
ok, thanks!
