### ISSUE TITLE
Uploading a small artifact just have PutObjectRequest hangs

### ISSUE THREAD

**Issue by lpezet** [ingenieux/beanstalker#74]
I'm still figuring things out but so far I had a `beanstalk:upload-source-bundle` hangs at the following line:
```
[INFO] Target Path: s3://....../my-bundle.zip
[INFO] Uploading artifact file: /...../my-bundle.zip
```

I specify a custom value for `artifactFile`. When I leave it as is (i.e. the actual .jar file of the project), it will upload just fine.
The problem seems to be related to the size of the file (my-bundle.zip) and the multipart upload...??
That my-bundle.zip file is 2181 bytes. If I set `multipartUpload` to false, it will work just fine.

Thoughts?

**Comment by aldrinleal** [comment]
Could be related to multipart indeed. Simply disable - multiparts are for larger slugs anyway

-----Original Message-----

**Comment by gabor-nagy** [comment]
I had the same problem, <multipartUpload>false</multipartUpload> solved it, thanks.
