### ISSUE TITLE
Update worker environment

### ISSUE THREAD

**Issue by mobiletoly** [ingenieux/beanstalker#78]
I'm not sure if this is an issue but I'm stuck. I have two components in my application. One is a regular beanstalk web app and another one is worker tier app. Updating/creating web tier app looks very straightforward

                <plugin>
                        <groupId>br.com.ingenieux</groupId>
                        <artifactId>beanstalk-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>deploy</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>upload-source-bundle</goal>
                                    <goal>create-application-version</goal>
                                    <goal>put-environment</goal>
                                    <goal>fast-deploy</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

but it is not the case with worker tier. Is it possible to set up goals so worker env will be created if it does not exist and updated with automatic deployment if it is already exists?

**Comment by aldrinleal** [comment]
Fast Deploy is not needed in this case. Can you look at the archetype's output and compare? I believe that for the latest version, it should work just fine

**Comment by mobiletoly** [comment]
Archetype provided a right set of goals, works as expected:

                            <goals>
                                <goal>upload-source-bundle</goal>
                                <goal>create-application-version</goal>
                                <goal>put-environment</goal>
                            </goals>
