### ISSUE TITLE
clean-previous-versions skips application versions belonging to other applications

### ISSUE THREAD

**Issue by jwilmoth** [ingenieux/beanstalker#89]
The clean-previous-versions goal reports EB app versions that it's skipping because it's bound to an environment which is great.  Because we use a naming convention for environments that aligns with the different EB applications being deployed, I noticed that it's not removing app versions because the same version is in use with another application's environment(s).  For example when running the goal for the "foundation sample service" application, 3 other environments are referenced and all three belong to different applications.

[INFO] VersionLabel 1.0.0.89 is bound to environment fnd-sample-svc-si-e3-0 - Skipping it
[INFO] VersionLabel 1.0.0.86 is bound to environment cust-message-svc-perf-A - Skipping it
[INFO] VersionLabel 1.0.0.71 is bound to environment rsp-sbtemplate-si-1 - Skipping it
[INFO] VersionLabel 1.0.0.82 is bound to environment rsp-boxaccess-si-1 - Skipping it

**Comment by aldrinleal** [comment]
It is better never to override an application version, since if you deploy the same version again, changes won't be picked up.

**Comment by jwilmoth** [comment]
I totally agree that versions within a single application should be unique and never overridden with new code.  The issue appears to be that applications A and B can both produce the same application versions (e.g. A - v1, v2, v3 B - v1, v2, v3).  If application B only has one environment with version 3, app B's versions 1 & 2 are skipped because they're bound to app A envs.  If I run the clean versions goal for application B, I'd expect versions 1&2 to be eligible for cleanup depending on retention filters.
