### ISSUE TITLE
update-environment dont use cnamePrefix

### ISSUE THREAD

**Issue by marcelalburg** [ingenieux/beanstalker#94]
Hello,

my name of the project is `<artifactId>parent</artifactId>` and if i run 

`mvn beanstalk:update-environment -Dbeanstalk.cnamePrefix=test-war`

he tries to connect to

```
[INFO] --- beanstalk-maven-plugin:1.4.3-foralula:update-environment (default-cli) @ parent ---
[INFO] ... with cname belonging to parent.elasticbeanstalk.com or parent.eu-central-1.elasticbeanstalk.com
[INFO] ... with status *NOT* set to 'Terminated'
```

i guess it should be a combination of cnamePrefix and regionName: http://test-war.eu-central-1.elasticbeanstalk.com

or if i do something wrong ?

Thanks 

Marcel

**Comment by aldrinleal** [comment]
cnamePrefix only applies when creating environments. You must use environmentRef set as whatever.elasticbeanstalk.com or whatever.region.elasticbeanstalk.com
