### ISSUE TITLE
How to deploy 2 different war files to different environments under one application

### ISSUE THREAD

**Issue by alexeigit** [ingenieux/beanstalker#95]
Hi, i have one beanstalk app that have 2 environments, have two different s3Buckets for my war files. When i try to deploy my two wars to each beanstalk environment, only one war deployed to both env.

I deploy every war from its project war folder :

mvn beanstalk-maven-plugin:upload-source-bundle beanstalk-maven-plugin:create-application-version beanstalk-maven-plugin:update-environment -Dbeanstalk.environmentRef=FIRST-env.elasticbeanstalk.com -Dbeanstalk.applicationName=myapp -Dbeanstalk.s3Bucket=FIRST-war-app

mvn beanstalk-maven-plugin:upload-source-bundle beanstalk-maven-plugin:create-application-version beanstalk-maven-plugin:update-environment -Dbeanstalk.environmentRef=SECOND-env.elasticbeanstalk.com -Dbeanstalk.applicationName=myapp -Dbeanstalk.s3Bucket=SECOND-war-app

**Comment by aldrinleal** [comment]
Whats the output of the wrong build? If you care, do with -X so we could look it up.

(We actually do profiles for this very same reason)

**Comment by aldrinleal** [comment]
Oh wait, there`s something missing: You haven't defined a versionLabel at all. If you don't define, beanstalker will always use the latest version uploaded, regardless of its location.

**Comment by alexeigit** [comment]
I defined it in parent base pom properties:
 <beanstalk.versionLabel>${project.version}</beanstalk.versionLabel>

1) beanstalk-maven-plugin:upload-source-bundle this goal upload source bundle to the right place

2) beanstalk-maven-plugin:create-application-version returns app version and source of first application, see it in log

> [INFO] --- beanstalk-maven-plugin:1.5.0:create-application-version (default-cli) @ pdx-dmp-management-web ---
> [DEBUG] Configuring mojo br.com.ingenieux:beanstalk-maven-plugin:1.5.0:create-application-version from plugin realm ClassRealm[plugin>br.com.ingenieux:beanstalk-maven-plugin:1.5.0, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
> [DEBUG] Configuring mojo 'br.com.ingenieux:beanstalk-maven-plugin:1.5.0:create-application-version' with basic configurator -->
> [DEBUG]   (f) applicationName = myapp
> [DEBUG]   (f) autoCreateApplication = true
> [DEBUG]   (f) credentialId = default
> [DEBUG]   (f) ignoreExceptions = false
> [DEBUG]   (f) regionName = us-west-2
> [DEBUG]   (f) s3Bucket = SECOND-app
> [DEBUG]   (f) s3Key = SECOND-app-web-0.1.19.war
> [DEBUG]   (f) serverId = aws.amazon.com
> [DEBUG]   (f) session = org.apache.maven.execution.MavenSession@61e3a1fd
> [DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@eadb475
> [DEBUG]   (f) skipExisting = true
> [DEBUG]   (f) verbose = false
> [DEBUG]   (f) versionDescription = Update from beanstalk-maven-plugin
> [DEBUG]   (f) versionLabel = 0.1.19
> [DEBUG] -- end configuration --

> [DEBUG] Receiving response: HTTP/1.1 200 OK
> [DEBUG] << HTTP/1.1 200 OK
> [DEBUG] << x-amzn-RequestId: 43a1e57d-0b88-11e6-bb6f-e18e70ceaeaa
> [DEBUG] << Content-Type: text/xml
> [DEBUG] << Content-Length: 903
> [DEBUG] << Date: Tue, 26 Apr 2016 08:24:15 GMT
> [DEBUG] Connection can be kept alive for 60000 MILLISECONDS
> [DEBUG] x-amzn-RequestId: 43a1e57d-0b88-11e6-bb6f-e18e70ceaeaa
> [DEBUG]  << "<"
> [DEBUG]  << "D"
> [DEBUG]  << "e"
> [DEBUG]  << "s"
> [DEBUG]  << "cribeApplicationVersionsResp"
> [DEBUG]  << "onse xmlns="http://elasticbeanstalk.amazonaws.com/docs/2010-12-01/">[\n]"
> [DEBUG]  << "  <DescribeApplicationVersionsResult>[\n]"
> [DEBUG]  << "    <ApplicationVersions>[\n]"
> [DEBUG]  << "      <member>[\n]"
> [DEBUG]  << "        <DateCreated>2016-04-22T12:29:10.317Z</DateCreated>[\n]"
> [DEBUG]  << "        <VersionLabel>0.1.19</VersionLabel>[\n]"
> [DEBUG]  << "        <SourceBundle>[\n]"
> [DEBUG]  << "          <S3Bucket>FIRST-app-bucket</S3Bucket>[\n]"
> [DEBUG]  << "          <S3Key>FIRST-app-web/FIRST-app-web-0.1.19.war</S3Key>[\n]"
> [DEBUG]  << "        </SourceBundle>[\n]"
> [DEBUG]  << "        <Description>SECOND-app-web</Description>[\n]"
> [DEBUG]  << "        <ApplicationName>myapp</ApplicationName>[\n]"
> [DEBUG]  << "        <Status>UNPROCESSED</Status>[\n]"
> [DEBUG]  << "        <DateUpdated>2016-04-26T08:12:06.991Z</DateUpdated>[\n]"
> [DEBUG]  << "      </member>[\n]"
> [DEBUG]  << "    </ApplicationVersions>[\n]"
> [DEBUG]  << "  </DescribeApplicationVersionsResult>[\n]"
> [DEBUG]  << "  <ResponseMetadata>[\n]"
> [DEBUG]  << "    <RequestId>43a1e57d-0b88-11e6-bb6f-e18e70ceaeaa</RequestId>[\n]"
> [DEBUG]  << "  </ResponseMetadata>[\n]"
> [DEBUG]  << "</DescribeApplicationVersionsResponse>[\n]
> [DEBUG] Connection [id: 10][route: {s}->https://elasticbeanstalk.us-west-2.amazonaws.com] can be kept alive for 60000 MILLISECONDS
> [DEBUG] Connection released: [id: 10][route: {s}->https://elasticbeanstalk.us-west-2.amazonaws.com][total kept alive: 1; route allocated: 1 of 50; total allocated: 1 of 50]
> [DEBUG] Received successful response: 200, AWS Request ID: 43a1e57d-0b88-11e6-bb6f-e18e70ceaeaa
> [INFO] VersionLabel 0.1.19 already exists. Skipping creation of new application-version
> [INFO] SUCCESS
> [INFO] null/void result

3) beanstalk-maven-plugin:update-environment update second environment with first web application

**Comment by alexeigit** [comment]
Resolved by adding property `<maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>`
and put timestamp to versionLabel, thanks for your help
